### PR TITLE
fix: lock to avoid potential data race in IrtCherenkovParticleID

### LINKED ISSUE #1937: Potential data race in IrtCherenkovParticleID
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): `1907-simcalorimeter-hit-contribution-time-after-simcalorimeterhitprocessor-should-include-travel-time` but expected in `main` too
- Which version (or `HEAD` for the most recent on git): `HEAD`
- Any specific OS or system where the issue occurs? CI
- Any special versions of ROOT or Geant4? no

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. https://github.com/eic/EICrecon/actions/runs/15934977296/job/44953482018?pr=1923#step:7:844

### Expected Result: (what do you expect when you execute the steps above)
No data race

### Actual Result: (what do you get when you execute the steps above)
Potential data race.

### Additional context
```
WARNING: ThreadSanitizer: data race (pid=51)
  Read of size 8 at 0x7b40000272f0 by thread T2 (mutexes: write M0):
    #0 std::vector<std::pair<double, double>, std::allocator<std::pair<double, double>>>::size() const /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:988:40 (libalgorithms_pid.so+0x2fb32) (BuildId: 753d9f6e1ffeed1e88a5cce057eb0aa01c735e0a)
    #1 std::vector<std::pair<double, double>, std::allocator<std::pair<double, double>>>::vector(std::vector<std::pair<double, double>, std::allocator<std::pair<double, double>>> const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:597:19 (libalgorithms_pid.so+0x2fb32)
    #2 eicrecon::IrtCherenkovParticleID::init(CherenkovDetectorCollection*) /home/runner/work/EICrecon/EICrecon/src/algorithms/pid/IrtCherenkovParticleID.cc:81:33 (libalgorithms_pid.so+0x2fb32)

  Previous write of size 8 at 0x7b40000272f0 by thread T3 (mutexes: write M1):
    #0 std::vector<std::pair<double, double>, std::allocator<std::pair<double, double>>>::_M_erase_at_end(std::pair<double, double>*) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1934:30 (libalgorithms_pid.so+0x2fc11) (BuildId: 753d9f6e1ffeed1e88a5cce057eb0aa01c735e0a)
    #1 std::vector<std::pair<double, double>, std::allocator<std::pair<double, double>>>::clear() /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1601:9 (libalgorithms_pid.so+0x2fc11)
    #2 eicrecon::IrtCherenkovParticleID::init(CherenkovDetectorCollection*) /home/runner/work/EICrecon/EICrecon/src/algorithms/pid/IrtCherenkovParticleID.cc:82:32 (libalgorithms_pid.so+0x2fc11)
    #3 eicrecon::IrtCherenkovParticleID_factory::Configure() /home/runner/work/EICrecon/EICrecon/src/factories/pid/IrtCherenkovParticleID_factory.h:69:13 (DRICH.so+0xd4909) (BuildId: 01327759661c36f032520b57718812573bd5c23e)

  Location is heap block of size 256 at 0x7b4000027200 allocated by main thread:
    #0 operator new(unsigned long) <null> (eicrecon+0xdbed7) (BuildId: 7f2d73720f97cb297614d241dd71b13dc8394696)
    #1 TStorage::ObjectAlloc(unsigned long) <null> (libCore.so.6.32+0x1fe8f8) (BuildId: 84b6391a6a81f360bf8aefa289212f88be1cf2f8)
    #2 CherenkovDetectorCollection::AddFlatRadiator(CherenkovDetector*, char const*, unsigned int, G4LogicalVolume const*, G4RadiatorMaterial const*, FlatSurface const*, double) /opt/local/include/IRT/CherenkovDetectorCollection.h:51:21 (richgeo.so+0x273eb) (BuildId: 6ac9bb493cadbd63caebb4970505be5ea2e4582f)
    #3 richgeo::IrtGeoDRICH::DD4hep_to_IRT() /home/runner/work/EICrecon/EICrecon/src/services/geometry/richgeo/IrtGeoDRICH.cc:81:58 (richgeo.so+0x22c96) (BuildId: 6ac9bb493cadbd63caebb4970505be5ea2e4582f)
    #4 richgeo::IrtGeoDRICH::IrtGeoDRICH(gsl::not_null<dd4hep::Detector const*>, gsl::not_null<dd4hep::rec::CellIDPositionConverter const*>, std::shared_ptr<spdlog::logger>) /home/runner/work/EICrecon/EICrecon/src/services/geometry/richgeo/IrtGeoDRICH.h:28:5 (richgeo.so+0x39ecf) (BuildId: 6ac9bb493cadbd63caebb4970505be5ea2e4582f)
```

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This PR fixes #1937 by adding more scoped lock_guards.

### What kind of change does this PR introduce?
- [x] Bug fix (issue #1937)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Review by veprbl — DISMISSED** [review]
LGTM, capybara report is clean

File: src/algorithms/pid/IrtCherenkovParticleID.h [hunk 1]
```diff
@@ -59,17 +59,17 @@ class IrtCherenkovParticleID : public IrtCherenkovParticleIDAlgorithm,
   void process(const Input&, const Output&) const;
 
 private:
+  // any access (R or W) to m_irt_det_coll, m_irt_det, m_pid_radiators must be locked
+  mutable std::mutex m_irt_det_mutex;
```
Comment (wdconinc) [inline src/algorithms/pid/IrtCherenkovParticleID.h:63]:
```suggestion
  inline static std::mutex m_irt_det_mutex;
```

File: src/algorithms/pid/IrtCherenkovParticleID.h [hunk 2]
```diff
@@ -59,17 +59,17 @@ class IrtCherenkovParticleID : public IrtCherenkovParticleIDAlgorithm,
   void process(const Input&, const Output&) const;
 
 private:
+  // any access (R or W) to m_irt_det_coll, m_irt_det, m_pid_radiators must be locked
+  inline static std::mutex m_irt_det_mutex;
```
Comment (veprbl) [inline src/algorithms/pid/IrtCherenkovParticleID.h:63]: Do we expect that DRICH and pfRICH geometries could be operated on orthogonally?

**Review by veprbl — APPROVED** [review]
LGTM
